# Generated by Django 4.1.7 on 2023-05-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=45)),
                ('tipo_entrega', models.CharField(max_length=45)),
                ('total', models.FloatField()),
                ('cliente_idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=150)),
                ('stock', models.IntegerField()),
                ('imagen', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_X_Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.pedido')),
                ('producto_idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.producto')),
            ],
        ),
    ]
