# Generated by Django 4.1.7 on 2023-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_pedido_x_producto_cantidad_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_x_producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
