# Generated by Django 4.1.7 on 2023-05-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id_clienteid',
            field=models.ForeignKey(db_column='id_clienteid_id', on_delete=django.db.models.deletion.CASCADE, to='persona.cliente'),
        ),
    ]
