# Generated by Django 4.1.7 on 2023-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_mascota_id_clienteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='verificado',
            field=models.BooleanField(default=0),
        ),
    ]
